<?php

namespace Transbank\WooCommerce\WebpayRest\Repositories;

use Transbank\WooCommerce\WebpayRest\Exceptions\DatabaseInsertException;
use Transbank\Plugin\Exceptions\RecordNotFoundOnDatabaseException;
use Transbank\WooCommerce\WebpayRest\Helpers\WpdbTableHelper;
use InvalidArgumentException;

class InscriptionRepository
{
    const TABLE_NAME = 'transbank_inscriptions';

    private WpdbTableHelper $db;

    public function __construct(WpdbTableHelper $wpdb)
    {
        $this->db = $wpdb;
    }

    /**
     * Get the name of the inscription database table with prefix.
     *
     * @return string The name of the table used to store inscriptions.
     */
    public function getTableName(): string
    {
        return $this->db->getTableName();
    }

    /**
     * Get the name of the inscription database table without prefix.
     *
     * @return string The name of the table used to store inscriptions.
     */

    public function getRawTableName(): string
    {
        return self::TABLE_NAME;
    }
    /**
     * Create a inscription record.
     *
     * @param array $data Inscription data to be stored.
     * @return object
     * @throws RecordNotFoundOnDatabaseException
     * @throws DatabaseInsertException
     */
    public function create(array $data)
    {
        if (empty($data)) {
            throw new InvalidArgumentException('No se proporcionaron datos para insertar.');
        }

        $inserted = $this->db->insert($data, 'Error al insertar en la tabla ');
        return $this->db->getOneOrFail(
            "SELECT * FROM `{$this->db->getTableName()}` WHERE id = %d",
            ['id' => $inserted],
            'No se pudo recuperar el registro insertado en la tabla ',
            true,
        );
    }

    /**
     * Update an existing inscription record by id.
     *
     * @param string $inscriptionId Token identifying the inscription.
     * @param array $data New data to update the transaction with.
     * @return int|false Number of rows updated or false on failure.
     */
    public function update(string $inscriptionId, array $data)
    {
        return $this->db->update(['id' => $inscriptionId], $data);
    }

    /**
     * Retrieve a inscription by token. Throws an exception if not found.
     *
     * @param string $token The inscription token.
     * @return object Inscription object
     * @throws RecordNotFoundOnDatabaseException
     */
    public function getByToken(string $token)
    {
        return $this->db->getOneOrFail(
            "SELECT * FROM `{$this->db->getTableName()}` WHERE `token` = %s",
            ['token' => $token],
            'Token no se encontró en la base de datos de inscripciones'
        );
    }

    /**
     * Retrieve a inscription by ID. Throws an exception if not found.
     *
     * @param string $id The inscription ID.
     * @return object Inscription object
     *
     * @throws RecordNotFoundOnDatabaseException
     */
    public function getById(string $id): object
    {
        $id = (int) $id;
        return $this->db->getOneOrFail(
            "SELECT * FROM `{$this->db->getTableName()}` WHERE `id` = %d",
            ['id' => $id],
            'No se encontró inscripción con el ID proporcionado'
        );
    }

    /**
     * Checks whether the database table exists.
     *
     * @return bool True if the table exists, false otherwise.
     */
    public function checkExistTable(): bool
    {
        return $this->db->tableExists();
    }

    /**
     * Returns the last database error generated by the most recent query.
     * @return string The last database error message, or an empty string if none.
     */
    public function getLastQueryError () : string {
        return $this->db->getLastQueryError();
    }
}
