<?php

namespace Transbank\WooCommerce\WebpayRest\Repositories;

use Transbank\Plugin\Helpers\TbkConstants;
use Transbank\Plugin\Model\TbkTransaction;
use Transbank\Plugin\Exceptions\RecordNotFoundOnDatabaseException;

use Transbank\WooCommerce\WebpayRest\Repositories\WpdbTableHelper;

class TransactionRepository
{
    const TABLE_NAME = 'webpay_rest_transactions';


    private WpdbTableHelper $db;

    public function __construct(WpdbTableHelper $wpdb)
    {
        $this->db = $wpdb;
    }

    /**
     * Get the name of the transaction database table.
     *
     * @return string The name of the table used to store transactions.
     */
    public function getTableName(): string
    {
        return $this->db->getTableName();
    }


    /**
     * Get the name of the transaction without prefix database table.
     *
     * @return string The name of the table used to store transactions.
     */
    public function getRawTableName(): string
    {
        return self::TABLE_NAME;
    }


    /**
     * Create a transaction record.
     *
     * @param TbkTransaction $data Transaction data to be stored.
     * @return mixed
     */
    public function create(TbkTransaction $data)
    {
        $transaction = [
            'order_id'    => $data->getOrderId(),
            'buy_order'   => $data->getBuyOrder(),
            'amount'      => $data->getAmount(),
            'environment' => $data->getEnvironment(),
            'commerce_code'  => $data->getCommerceCode(),
            'product'     => $data->getProduct(),
            'status'      => $data->getStatus(),

            'token'       => $data->getToken(),
            'session_id'  => $data->getSessionId(),

            'child_buy_order' => $data->getChildBuyOrder(),
            'child_commerce_code' => $data->getChildCommerceCode()
        ];


        $inserted = $this->db->insert($transaction);
        return $this->db->getOneOrFail(
            "SELECT * FROM `{$this->db->getTableName()}` WHERE id = %d",
            ['id' => $inserted],
            'No se pudo recuperar el registro insertado en la tabla ',
            true,
        );
    }

    /**
     * Update an existing transaction record by id.
     *
     * @param string $transactionId Token identifying the transaction.
     * @param array $data New data to update the transaction with.
     * @return mixed
     */
    public function update(string $transactionId, array $data)
    {
        return $this->db->update(['id' => $transactionId], $data);
    }

    /**
     * Retrieve a transaction by token. Throws an exception if not found.
     *
     * @param string $token The transaction token.
     * @return mixed
     */
    public function getByToken(string $token)
    {
        return $this->db->getOne(
            "SELECT * FROM `{$this->db->getTableName()}` WHERE `token` = %s",
            ['token' => $token],
        );
    }

    /**
     * Retrieve a transaction by buyOrder. Throws an exception if not found.
     *
     * @param string $buyOrder The buy order associated with the transaction.
     * @return mixed
     * @throws RecordNotFoundOnDatabaseException
     */
    public function getByBuyOrder(string $buyOrder)
    {

        return $this->db->getOneOrFail(
            "SELECT * FROM `{$this->db->getTableName()}` WHERE `buy_order` = %s",
            ['buy_order' => $buyOrder],
            'BuyOrder no se encontró en la base de datos de transacciones'
        );
    }

    /**
     * Retrieve the first approved transaction by orderId.
     *
     * @param string $orderId
     * @return mixed|null
     */
    public function findFirstApprovedByOrderId(string $orderId)
    {
        $statusApproved = TbkConstants::TRANSACTION_STATUS_APPROVED;
        return $this->db->getOne(
            "SELECT * FROM `{$this->db->getTableName()}` WHERE `status` = %s AND `order_id` = %d",
            [
                'status' => $statusApproved,
                'order_id' => (int)$orderId,
            ],
        );
    }

    /**
     * Retrieve the first transaction by orderId.
     *
     * @param mixed $orderId
     * @return object|null
     */
    public function findFirstByOrderId($orderId): ?object
    {
        return $this->db->getOne(
            "SELECT * FROM `{$this->db->getTableName()}` WHERE `order_id` = %s ORDER BY id DESC",
            [
                'order_id' => $orderId,
            ],
        );
    }

    /**
     * Checks whether the database table exists.
     *
     * @return bool True if the table exists, false otherwise.
     */
    public function checkExistTable(): bool
    {
        return $this->db->tableExists();
    }

    /**
     * Returns the last database error generated by the most recent query.
     * @return string The last database error message, or an empty string if none.
     */
    public function getLastQueryError(): string
    {
        return $this->db->getLastQueryError();
    }
}
