name: Build and Scan
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "master"

permissions:
  contents: read
  pull-requests: write

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1
        with:
          php-version: "8.2"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Package Plugin
        shell: bash
        run: |
          set -Eeuo pipefail
          chmod +x package.sh
          ./package.sh
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload zip artifact
        if: success()
        id: upload_zip
        uses: actions/upload-artifact@v4
        with:
          name: transbank-plugin-zip
          path: transbank-webpay-plus-rest.zip
      - name: Comment PR with artifact link
        if: success() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@70d2764d1a7d5d9560b100cbea0077fc8f633987
        with:
          header: plugin-zip
          message: |
            Plugin ZIP disponible.

            - Descargar artifact: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload_zip.outputs.artifact-id }}
